server: 
  port: 8080
  servlet: 
    context-path: /api
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://auth.bagarote.com.br/auth/realms/bagarote-desafio
          jwk-set-uri: https://auth.bagarote.com.br/auth/realms/bagarote-desafio/protocol/openid-connect/certs
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/desafio}
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:123456}
    driver-class-name: org.postgresql.Driver